changelog:
  categories:
    - title: Highlights
      labels:
        - release
    - title: Documentation
      labels:
        - docs
    - title: Workflow
      labels:
        - workflow
  exclude:
    labels:
      - skip-changelog
